name: Codespell

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install codespell
        run: pip install codespell

      - name: Run codespell
        run: |
          # Use cspell with .cspell.json config
          cspell --config .cspell.json "**/*.{py,md,yaml,yml,json,toml}"
